In [16]:
import open3d as o3d
import numpy as np

seg_name='/home/sid/data/sets/nuscenes/lidarseg/v1.0-mini/4484110755904050a880043268149497_lidarseg.bin'
seg=np.fromfile(seg_name, dtype=np.uint8)
print(seg_name)
color = np.zeros([len(seg), 3])
color[:, 0] = seg/32
color[:, 1] = seg/32
color[:, 2] = seg/32

pcd_name='/home/sid/data/sets/samples/LIDAR_TOP/n008-2018-08-28-16-43-51-0400__LIDAR_TOP__1535489296047917.pcd.bin'
print(pcd_name)
scan=np.fromfile(pcd_name, dtype=np.float32)
points = scan.reshape((-1, 5))[:, :4]

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points[:, :3])
#pcd.colors = o3d.utility.Vector3dVector(color)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd])

/home/sid/data/sets/samples/LIDAR_TOP/n008-2018-08-28-16-43-51-0400__LIDAR_TOP__1535489296047917.pcd.bin
(172000,)
[[ 0.03125    -0.06875     0.13124999]
 [ 0.03125    -0.06875     0.13124999]
 [ 0.03125    -0.06875     0.13124999]
 ...
 [ 0.1875      0.0875      0.28749999]
 [ 0.09375    -0.00625     0.19374999]
 [ 1.3125      1.21249998  1.41250002]]
[[ -0.46375105   0.02599042  -0.27544802]
 [ -2.50860596   0.14160646  -1.41172695]
 [ -2.46654415   0.14006428  -1.31359327]
 ...
 [-21.57385063   0.06398946   3.03202438]
 [-21.52137566   0.06763607   3.53584981]
 [-21.52715302   0.07517076   4.05594397]]


In [ ]:
import open3d as o3d
import numpy as np
pcd_name='/home/sid/data/sets/samples/LIDAR_TOP/n008-2018-08-28-16-43-51-0400__LIDAR_TOP__1535489296047917.pcd.bin'
print(pcd_name)
scan=np.fromfile(pcd_name, dtype=np.float32)
print(scan.shape)
points = scan.reshape((-1, 5))[:, :4]
intens = abs(points[:,3])
color = np.zeros([len(intens), 3])
color[:, 0] = intens/32
color[:, 1] = intens/32 - 0.1
color[:, 2] = intens/32 + 0.1

print(color)


pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points[:, :3])
pcd.colors = o3d.utility.Vector3dVector(color)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd])

In [ ]:
import open3d as o3d
import numpy as np
pcd_name='/home/sid/data/sets/samples/LIDAR_TOP/n008-2018-08-28-16-43-51-0400__LIDAR_TOP__1535489296047917.pcd.bin'
print(pcd_name)
scan=np.fromfile(pcd_name, dtype=np.float32)
print(scan.shape)
points = scan.reshape((-1, 5))[:, :4]
intens = points[:,3]
height = abs(points[:,2])

color = np.zeros([len(intens), 3])
color[:, 0] = height/10
color[:, 1] = height/10 - 0.1
color[:, 2] = height/10 - 0.3

print(color)

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points[:, :3])
pcd.colors = o3d.utility.Vector3dVector(color)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd])

In [18]:
import open3d as o3d
import numpy as np

seg_name='/home/sid/data/sets/nuscenes/lidarseg/v1.0-mini/4484110755904050a880043268149497_lidarseg.bin'
seg=np.fromfile(seg_name, dtype=np.uint8)
print(seg_name)
color = np.zeros([len(seg), 3])
color[:, 0] = seg/32
color[:, 1] = seg/32
color[:, 2] = seg/32

pcd_name='/home/sid/data/sets/samples/LIDAR_TOP/n008-2018-08-28-16-43-51-0400__LIDAR_TOP__1535489296047917.pcd.bin'
print(pcd_name)
scan=np.fromfile(pcd_name, dtype=np.float32)
points = scan.reshape((-1, 5))[:, :4]

pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(points[:, :3])
pcd.colors = o3d.utility.Vector3dVector(color)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd])

/home/sid/data/sets/nuscenes/lidarseg/v1.0-mini/4484110755904050a880043268149497_lidarseg.bin
/home/sid/data/sets/samples/LIDAR_TOP/n008-2018-08-28-16-43-51-0400__LIDAR_TOP__1535489296047917.pcd.bin
[[ -0.46375105   0.02599042  -0.27544802]
 [ -2.50860596   0.14160646  -1.41172695]
 [ -2.46654415   0.14006428  -1.31359327]
 ...
 [-21.57385063   0.06398946   3.03202438]
 [-21.52137566   0.06763607   3.53584981]
 [-21.52715302   0.07517076   4.05594397]]
